export const rodentTypes = [
  "mut/unknown",
  "chinchilla",
  "gerbil",
  "guinea pig",
  "hamster",
  "mouse",
  "rabbit",
  "rat",
];

export const lizardTypes = [
  "mut/unknown",
  "bearded dragon",
  "blue-tongued skink",
  "chameleon",
  "green anole",
  "grested gecko",
  "iguana",
  "leopard gecko",
  "monitor lizard",
  "tegu lizard",
  "uromastyx",
];

export const dogBreeds = [
  "mut/unknown",
  "affenpinscher",
  "afghan hound",
  "african",
  "airedale",
  "akita",
  "american terrier",
  "appenzeller",
  "australian cattledog",
  "australian terrier",
  "basenji",
  "basset hound",
  "beagle",
  "bedlington terrier",
  "bernese mountain",
  "bichon frise",
  "blenheim spaniel",
  "blood hound",
  "bluetick",
  "border collie",
  "border terrier",
  "borzoi",
  "boston bulldog",
  "bouvier",
  "boxer",
  "brabancon",
  "briard",
  "brittany spaniel",
  "bull mastiff",
  "cairn terrier",
  "cardigan corgi",
  "caucasian ovcharka",
  "chesapeake retriever",
  "chihuahua",
  "chow",
  "clumber",
  "cockapoo",
  "cocker spaniel",
  "coonhound",
  "cotondetulear",
  "curly retriever",
  "dachshund",
  "dalmatian",
  "dandie terrier",
  "dhole",
  "dingo",
  "doberman",
  "english bulldog",
  "english hound",
  "english mastiff",
  "english setter",
  "english sheepdog",
  "english springer",
  "entlebucher",
  "eskimo",
  "flat-coated retriever",
  "fox terrier",
  "french bulldog",
  "german pointer",
  "german longhair pointer",
  "german shepherd",
  "giant schnauzer",
  "golden retriever",
  "gordon setter",
  "great dane",
  "greyhound",
  "groenendael",
  "havanese",
  "husky",
  "ibizan hound",
  "irish setter",
  "irish spaniel",
  "irish terrier",
  "irish wolfhound",
  "italian greyhound",
  "italian segugio",
  "japanese spaniel",
  "japanese spitz",
  "keeshond",
  "kelpie",
  "kerryblue terrier",
  "komondor",
  "kuvasz",
  "labradoodle",
  "labrador",
  "lakeland terrier",
  "lapphund finnish",
  "leonberg",
  "lhasa",
  "malamute",
  "malinois",
  "maltese",
  "medium poodle",
  "mexican hairless",
  "miniature pinscher",
  "miniature poodle",
  "miniature schnauzer",
  // "mix",
  "newfoundland",
  "norfolk terrier",
  "norwegian buhund",
  "norwegian elkhound",
  "norwich terrier",
  "otterhound",
  "papillon",
  "patterdale terrier",
  "pekinese",
  "pembroke",
  "pitbull",
  "plott hound",
  "pomeranian",
  "pug",
  "puggle",
  "pyrenees",
  "redbone",
  "rhodesian ridgeback",
  "rottweiler",
  "russell terrier",
  "saluki",
  "samoyed",
  "schipperke",
  "scottish deerhound",
  "scottish terrier",
  "sealyham terrier",
  "sharpei",
  "shepherd australian",
  "shetland sheepdog",
  "shiba",
  "shihtzu",
  "silky terrier",
  "spanish waterdog",
  "staffordshire bullterrier",
  "standard poodle",
  "stbernard",
  "sussex spaniel",
  "swiss mountain",
  "tervuren",
  "tibetan mastiff",
  "tibetan terrier",
  "toy poodle",
  "toy terrier",
  "vizsla",
  "walker hound",
  "weimaraner",
  "welsh spaniel",
  "welsh terrier",
  "westhighland terrier",
  "wheaten terrier",
  "whippet",
  "yorkshire terrier",
];

export const catBreeds = [
  "mut/unknown",
  "abyssinian",
  "aegean",
  "american bobtail",
  "american curl",
  "american shorthair",
  "american wirehair",
  "aphrodite giant",
  "arabian mau",
  "asian",
  "asian semilonghair",
  "australian mist",
  "balinese",
  "bambino",
  "bengal",
  "birman",
  "bombay",
  "brazilian shorthair",
  "british longhair",
  "british shorthair",
  "burmese",
  "burmilla",
  "california spangled",
  "chantilly-tiffany",
  "chartreux",
  "chausie",
  "colorpoint shorthair",
  "cornish rex",
  "cymric",
  "cyprus",
  "devon rex",
  "donskoy",
  "dragon li",
  "dwelf",
  "egyptian mau",
  "european shorthair",
  "exotic shorthair",
  "foldex",
  "german rex",
  "havana brown",
  "highlander",
  "himalayan",
  "japanese bobtail",
  "javanese",
  "khao manee",
  "korat",
  "korean bobtail",
  "korn ja",
  "kurilian bobtail",
  "lambkin",
  "laperm",
  "lykoi",
  "maine coon",
  "manx",
  "mekong bobtail",
  "minskin",
  "minuet",
  "munchkin",
  "nebelung",
  "neva masquerade",
  "norwegian forest cat",
  "ocicat",
  "ojos azules",
  "oriental bicolor",
  "oriental longhairg",
  "oriental shorthairg",
  "persian",
  "peterbald",
  "pixiebob",
  "ragamuffin",
  "ragdoll",
  "russian blue",
  "tabby",
  "sam sawet",
  "savannah",
  "scottish fold",
  "selkirk rex",
  "serengeti",
  "siamese",
  "siberian",
  "singapura",
  "snowshoe",
  "sokoke",
  "somali",
  "sphynx",
  "suphalak",
  "thai",
  "thai lilac",
  "tonkinese",
  "toybob",
  "toyger",
  "turkish angora",
  "turkish van",
  "turkish vankedisi",
  "ukrainian levkoy",
  "york chocolate",
];

// TO GENERATE DOG BREEDS
// export function parseDogBreeds() {
//   const myObj = {
//     affenpinscher: [],
//     african: [],
//     airedale: [],
//     akita: [],
//     appenzeller: [],
//     australian: ["shepherd"],
//     basenji: [],
//     beagle: [],
//     bluetick: [],
//     borzoi: [],
//     bouvier: [],
//     boxer: [],
//     brabancon: [],
//     briard: [],
//     buhund: ["norwegian"],
//     bulldog: ["boston", "english", "french"],
//     bullterrier: ["staffordshire"],
//     cattledog: ["australian"],
//     chihuahua: [],
//     chow: [],
//     clumber: [],
//     cockapoo: [],
//     collie: ["border"],
//     coonhound: [],
//     corgi: ["cardigan"],
//     cotondetulear: [],
//     dachshund: [],
//     dalmatian: [],
//     dane: ["great"],
//     deerhound: ["scottish"],
//     dhole: [],
//     dingo: [],
//     doberman: [],
//     elkhound: ["norwegian"],
//     entlebucher: [],
//     eskimo: [],
//     finnish: ["lapphund"],
//     frise: ["bichon"],
//     germanshepherd: [],
//     greyhound: ["italian"],
//     groenendael: [],
//     havanese: [],
//     hound: [
//       "afghan",
//       "basset",
//       "blood",
//       "english",
//       "ibizan",
//       "plott",
//       "walker",
//     ],
//     husky: [],
//     keeshond: [],
//     kelpie: [],
//     komondor: [],
//     kuvasz: [],
//     labradoodle: [],
//     labrador: [],
//     leonberg: [],
//     lhasa: [],
//     malamute: [],
//     malinois: [],
//     maltese: [],
//     mastiff: ["bull", "english", "tibetan"],
//     mexicanhairless: [],
//     mix: [],
//     mountain: ["bernese", "swiss"],
//     newfoundland: [],
//     otterhound: [],
//     ovcharka: ["caucasian"],
//     papillon: [],
//     pekinese: [],
//     pembroke: [],
//     pinscher: ["miniature"],
//     pitbull: [],
//     pointer: ["german", "germanlonghair"],
//     pomeranian: [],
//     poodle: ["medium", "miniature", "standard", "toy"],
//     pug: [],
//     puggle: [],
//     pyrenees: [],
//     redbone: [],
//     retriever: ["chesapeake", "curly", "flatcoated", "golden"],
//     ridgeback: ["rhodesian"],
//     rottweiler: [],
//     saluki: [],
//     samoyed: [],
//     schipperke: [],
//     schnauzer: ["giant", "miniature"],
//     segugio: ["italian"],
//     setter: ["english", "gordon", "irish"],
//     sharpei: [],
//     sheepdog: ["english", "shetland"],
//     shiba: [],
//     shihtzu: [],
//     spaniel: [
//       "blenheim",
//       "brittany",
//       "cocker",
//       "irish",
//       "japanese",
//       "sussex",
//       "welsh",
//     ],
//     spitz: ["japanese"],
//     springer: ["english"],
//     stbernard: [],
//     terrier: [
//       "american",
//       "australian",
//       "bedlington",
//       "border",
//       "cairn",
//       "dandie",
//       "fox",
//       "irish",
//       "kerryblue",
//       "lakeland",
//       "norfolk",
//       "norwich",
//       "patterdale",
//       "russell",
//       "scottish",
//       "sealyham",
//       "silky",
//       "tibetan",
//       "toy",
//       "welsh",
//       "westhighland",
//       "wheaten",
//       "yorkshire",
//     ],
//     tervuren: [],
//     vizsla: [],
//     waterdog: ["spanish"],
//     weimaraner: [],
//     whippet: [],
//     wolfhound: ["irish"],
//   };
//   var res = [];
//   for (var breed in myObj) {
//     if (myObj[breed].length === 0) {
//       res.push(breed);
//     } else {
//       const temp = breed;
//       myObj[breed].map((i) => res.push(i + " " + temp));
//     }
//   }
//   return res;
// }
